name: Valet Pro Max test pipeline

on:
  push:
    branches: [ 0.x ]
  pull_request:
    branches: [ 0.x ]

jobs:
  test:
    # Build on Monterey and later Ventura (Not public released yet: https://github.com/actions/runner-images)
    strategy:
      matrix:
        os: [macos-14]
#        php: ['8.3', '8.2', '8.1', '8.0', '7.4', '7.3', '7.2', '7.1']
        php: ['8.2']
    runs-on: ${{matrix.os}}
    name: ${{matrix.os}} with ${{matrix.php}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: '[INSTALL] Install PHP 7.4'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: dom, curl, libxml, mbstring, zip, fileinfo
          ini-values: error_reporting=E_ALL, max_execution_time=-1, memory_limit=512M
          tools: composer:v2
          coverage: none

      - name: '[INSTALL] Brew setup'
        run: |
          # Temporary fix, see https://github.com/actions/setup-python/issues/577
          rm -f /usr/local/bin/2to3 || true
          rm -f /usr/local/bin/2to3-3.12 || true
          rm -f /usr/local/bin/idle3 || true
          rm -f /usr/local/bin/idle3.12 || true
          rm -f /usr/local/bin/pydoc3 || true
          rm -f /usr/local/bin/pydoc3.12 || true
          rm -f /usr/local/bin/python3 || true
          rm -f /usr/local/bin/python3.12 || true
          rm -f /usr/local/bin/python3-config || true
          rm -f /usr/local/bin/python3.12-config || true

      - name: '[CACHE] Handle brew deps'
        uses: actions/cache@v4.0.0
        with:
          # Paths to cache:
          # /usr/local/Homebrew - installation folder of Homebrew
          # /usr/local/Cellar - installation folder of Homebrew formulae
          # /usr/local/Frameworks, /usr/local/bin, /usr/local/opt - contain (links to) binaries installed by Homebrew formulae
          # /usr/local/lib/python3.12 - Python3 packages installation
          path: |
            /usr/local/Homebrew
            /usr/local/Cellar
            /usr/local/Frameworks
            /usr/local/bin
            /usr/local/opt
            /usr/local/lib/python3.12
          key: ${{matrix.os}}-build-cache-${{ hashFiles('./valet') }}-v0

      - name: '[INSTALL] Composer install'
        run: composer install --no-dev --no-interaction --prefer-dist

      - name: '[INSTALL] Valet install'
        run: ./valet install

      - name: '[TEST] Nginx'
        run: |
          sudo nginx -t
          curl 127.0.0.1 | grep "Valet - Not Found"

      - name: '[TEST] DB commands'
        run: |
          ./valet db create testci | grep "\"testci\" created successfully"
          ./valet db list | grep "testci"
          ./valet db drop testci -y | grep "\"testci\" dropped successfully"

      - name: '[TEST] PHP switch'
        run: |
          brew unlink php || true
          brew link --overwrite php@7.4 --force || true
          ./valet use ${{matrix.php}} --force
          php -v | grep ${{matrix.php}}

      - name: '[TEST] xdebug on and off'
        run: |
          ./valet xdebug on
          ./valet xdebug off

      - name: '[TEST] memcache on and off'
        run: |
          ./valet memcache on
          ./valet memcache off
